### ISSUE TITLE
Cora，Citeseer，Pubmed 

### ISSUE THREAD

**Issue by ChengLeiYu-Maker** [qitianwu/DIFFormer#10]
在通过代码中给到的对三个数据运行代码sh，运行出来之后并没有达到论文中的效果。会不会跟包的版本有关系。但是我用了包里提示requirement.txt 会出现site-packages/torch_sparse/_convert_cuda.so: undefined symbol:_ZNSt15__exception_ptr13exception_ptr9_M_addrefEv

**Comment by qitianwu** [comment]
您好，应该是版本不匹配的问题吧。需要先安装torch sparse几个包，最后再安装pytorch geometric

**Comment by ChengLeiYu-Maker** [comment]
pip install torch-scatter torch-sparse torch-cluster torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.9.0+cu102.html
pip install torch-geometric
我是按照这个顺序装的

**Comment by qitianwu** [comment]
你看看这几个包的版本是否和requirement.txt里的一致，还有你安装的cuda版本，torch版本是否能对应上

**Comment by ChengLeiYu-Maker** [comment]
一致的然后出现了│Segmentation fault (core dumped) 的问题。不知道方不方便提供一个doker，针对这三个数据的。Citeseer这个数据我版本不一样跑出来差的太多了。

**Comment by qitianwu** [comment]
hello, 不知道你的问题是否已经解决了。docker文件因为太大所以不方便共享。我自己测过几次也收集了其他同学的反馈，如果版本一致操作正确的话复现结果是没问题的。如果出现了问题，大概就是以下几个原因：

1. 环境不一致（这个不会导致太大的偏差）
2. 数据集版本不一致
3. 没有按照提供的脚本使用正确的超参，或者没有使用提供的数据预处理/训练代码运行模型
