### ISSUE TITLE
cifar stl10数据训练结果

### ISSUE THREAD

**Issue by fengxiang6666** [qitianwu/DIFFormer#14]
你好，有一个问题想请教一下，我将数据导入之后，运行调试使用不同模型进行对比结果，发现使用gcn或者其他的模型呈现的结果和论文中的基本一致，但是使用difformer模型训练后得到的结果和论文中结果出入太大是什么情况呢？所用到的package是按照requirment下载的，不知道哪里出问题了？非常感谢可以解答。

**Comment by qitianwu** [comment]
你好！不好意思之前遗漏了回复，请问现在问题解决了吗？ 如果没有的话，你用的是什么运行命令，是代码里run.sh提供的命令吗？

**Comment by fengxiang6666** [comment]
很高兴收到您的回复，我们是直接运行的main.py，参数的调优是直接在parse.py修改，目前的代码我们不能直接运行run.sh文件，不直接运行run.sh文件对效果有影响吗？再次感谢您的回复。



在 2024-05-10 13:18:55，"Qitian Wu" ***@***.***> 写道：

你好！不好意思之前遗漏了回复，请问现在问题解决了吗？ 如果没有的话，你用的是什么运行命令，是代码里run.sh提供的命令吗？

**Comment by qitianwu** [comment]
用parse.py进行修改的话，得对着run.sh的超参数进行设置，有的action='store_true'的超参数需要设置为True才行

**Comment by fengxiang6666** [comment]
非常感谢您的解答，已经在调试过程，目前看问题已经解决，再次感谢。
