### ISSUE TITLE
code

### ISSUE THREAD

**Issue by zhu011** [qitianwu/DIFFormer#2]
很棒的工作，看了代码我有些问题，如果要处理图片的话，需要对代码进行改动吗？对维度进行修改吗

**Comment by qitianwu** [comment]
hi 我们这里的图片数据集是先使用由自监督方法预训练好的网络得到图片的表征作为input feature x。后面直接使用x作为DIFFormer输入。 如果你是想考虑raw image作为输入的话，可以考虑把DIFFormer接在一个backbone（如CNN/Vision Transformer）的后面，即使用backbone输出的embedding作为DIFFormer的输入。不过这样我没试过效果会如何

**Comment by zhu011** [comment]
谢谢您的解答，不过backbone的输出一般是[b,n,h,w],您的bifformer的输入x: input node features [N, D]D应该如何设置，以及qs: query tensor [N, H, M]ks: key tensor [L, H, M]，vs: value tensor [L, H, D]中的各个参数原谅我没看懂。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qitianwu/DIFFormer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月10日(星期三) 晚上10:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qitianwu/DIFFormer] code (Issue #2)





 
hi 我们这里的图片数据集是先使用由自监督方法预训练好的网络得到图片的表征作为input feature x。后面直接使用x作为DIFFormer输入。 如果你是想考虑raw image作为输入的话，可以考虑把DIFFormer接在一个backbone（如CNN/Vision Transformer）的后面，即使用backbone输出的embedding作为DIFFormer的输入。不过这样我没试过效果会如何

**Comment by qitianwu** [comment]
一般需要对backbone输出的feature map进行flatten得到每张图片instance对应的一维表征向量。我们DIFFormer class的输入x是一个[N, D]维度的数据，N表示节点数目，D是输入特征维度。放在你考虑的例子里，N应该是图片的数量，D是图片一维表征向量的维度。

关于qs/ks/vs，这里的N/L都是token数目（即节点数目），H是head数目，D/M是隐空间维度。使用不同的变量N/L和D/M是为了有所区分，但在我们的使用场景中N=L，D=M

**Comment by zhu011** [comment]
> 
好的好的，谢谢您的解答！

**Comment by lijinrun** [comment]
> 

您好，首先非常感谢您的工作，我想请问如何处理batch这一维度呢？我现在的输入X的shape是(batch, hidden_dim, N)，我尝试通过X.reshape(-1,N).transpose(0,1)来对输入进行维度变换，然后输入到模型中，模型返回后再变换回原来的shape，但是这样效果非常差。后来我尝试将batch设置为1，那么X的shape为(1, hidden_dim, N)，通过X.squeeze().transpose(0,1)后输入模型返回结果，效果就非常好。
但是还是希望您能帮忙提供一个处理batch的方法，非常感谢您。
