### ISSUE TITLE
cifar10数据怎么处理成features.pkl的，这个是怎么处理的

### ISSUE THREAD

**Issue by lhyvip** [qitianwu/DIFFormer#5]

**Comment by lhyvip** [comment]
对于两个图像数据集 CIFAR 和 STL，我们使用自监督预训练模型（ResNet-18）来获取图像的嵌入作为输入特征，，这里resnet-18这里是怎么操作的

**Comment by qitianwu** [comment]
Hi 我们使用的是torchvision提供的resnet18模块，使用SimCLR算法进行训练，把网络的输出向量作为我们的模型的输入，即features.pkl（维度是[N, D], 包含了N个样本的D维输入特征）

具体的训练和用法跟SimCLR的这个实现是一样的：https://github.com/Spijkervet/SimCLR/blob/master/main.py。
