### ISSUE TITLE
diffusion

### ISSUE THREAD

**Issue by ChengLeiYu-Maker** [qitianwu/DIFFormer#8]
你们的工作非常有趣，将diffusion 跟能量和图相结合。但是我并没有在代码中看到类似于图生成的denoise过程和计算能量降低的过程。希望您能够在代码中帮忙指出与对应论文中Energy Function 和Diffusivity S 对应的代码。
非常感谢！

**Comment by qitianwu** [comment]
Hi, 我们不是做的生成任务，这里的diffusion不是生成模型中研究的概率扩散模型，而是一般意义上的扩散过程，即热传导方程所描述的信号变化。我们进一步考虑的是由N个节点构成的离散空间中的扩散过程，具体的可以阅读中文的[Blog](https://zhuanlan.zhihu.com/p/622970740)或者我们的[Paper](https://arxiv.org/pdf/2301.09474.pdf)。

其次，diffusion和能量约束都是模型推导过程的motivation，不是最终的模型。最终的模型是最后由diffusivity启发得到的attention。两种diffusivity attention的实现在difformer.py的[这里](https://github.com/qitianwu/DIFFormer/blob/0b3fbc67c470faba95e079b7b6e95655f8a91a14/node%20classification/difformer.py#L10-L61)
